# Synthetic Data : A Very Brief Intro to a Very Exciting Area of Data Science
You’ve probably heard of deep fakes in the last few years - If not, on which side of the internet are you?

Sites like thispersondoesnotexist.com generate what we call synthetic data. In the case of this site, images of people who don’t exist. The images generated by the neural network are subjacent to the website. This neural network was trained on real images to create fake ones. 
